- pyramid_jsonapi/__init__.py
- Allows easily adding/modifying/removing endpoints and http_methods
- routes and views constructed from ENDPOINTS dictionary
- Makes code more DRY
Example, using this approach to handle OPTIONS requests for CORS:
```
def options_view(self):
return ''
for endpoint in pyramid_jsonapi.ENDPOINTS:
pyramid_jsonapi.ENDPOINTS[endpoint]['http_methods']['OPTIONS'] = {'function': 'options',
'renderer': 'string'}
pyramid_jsonapi.create_jsonapi(config,
models,
dbsession)
for vc in pyramid_jsonapi.view_classes.values():
vc.options = options_view
> Automate endpoint construction from structured data

- .travis.yml
- pyramid_jsonapi/__init__.py
- test_project/test_project/__init__.py
Major changes alert!
Overhauled module to make it class-based. Commit summary from main commit here:
Refactor module as classes.
- Pyramid_JSONAPI() allows  multiple API instances.
- MetaData() encapsulates endpoints data and route/view methods.
- Makes module use more flexible.
- config, models and get_dbsession are now instance attributes
- metadata and view_classes explicitly added to CollectionView
Have had to manually merge the hybrid changes in, as indentation makes automatic diffs tricky.
Tests are passing, but might want to review those areas from your recent commits for any gotchas.
> Class overhaul

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/schema/jsonapi-schema.json
- setup.py
- test_project/setup.py
- test_project/test_project/tests.py
* Validate request data - raise BadRequest on error
* Skip PATCH requests (subset of main schema).
* Default validation against jsonapi.org provided schema.
* Config options to toggle validation, and provide schema file.
* `pyramid_jsonapi.schema_validation`
* `pyramid_jsonapi.schema_file`
* No response validation currently, due to false-positives.
* Test updates to meet spec and expect validation errors.
> Validation using jsonschema

- pyramid_jsonapi/__init__.py
- test_project/test_project/tests.py
Currently, DELETE against a non-existent resource returns 200. The specification says:
> A server SHOULD return a 404 Not Found status code if a deletion request fails due to the resource not existing.
Update code to match this spec. Given that this is a `SHOULD` there may be a reason you are returning 200 I'm missing, so happy to stand corrected!
An additional failure case is where sqlalchemy raises a `DataError` exception, caused by the requested id failing to match the DB schema (e.g. requesting `cat` when the id column is type `int`).
I've opted to also return `404` here, rather than `400 Bad Request` as it is technically true, and it feels safer than trying to pass the sqlalchemy exception message to the client (and potentially reveal more about the underlying DB than might be …
> Handle DELETE errors according to spec

- pyramid_jsonapi/__init__.py
- test_project/test_project/tests.py
Look up `id_col_name`.
- Also add test
> Fixes #56 (post fails with primary key not called 'id')

- setup.py
Looks like the `requires` list was never actually being passed to `setup()`
> Add requires to install_requires

- pyramid_jsonapi/endpoints.py
Config settings are useful in other places which have access to the EndpointData instance. e.g. `api_prefix` is needed in swagger for `basePath`.
> Make instance attrs from config for access elsewhere.

- pyramid_jsonapi/endpoints.py
The test for empty strings allows the final component to be empty, and as a result the separator can be added to the end, i.e.: `metadata_pattern('foo', '')` will result in a pattern `/metadata/foo/`
'pyramid' treats trailing separators as explicit, so `http://example.com/metadata/foo` won't match this pattern.
> Prevent trailing separators.

- .gitattributes
- setup.py
- version.py
Drop setuptools_scm and switch to the simpler [version.py](https://github.com/Changaco/version.py)
This also allows versioning to be extracted from git archives, so that packages can require any tagged release from github, irrespective of pypi support, .i.e.:
```
dependency_links = [
'https://github.com/colinhiggs/pyramid-jsonapi/archive/1.0.3.post20.zip#egg=pyramid-jsonapi-1.0.3.post20',
]
requires = [
'pyramid_jsonapi == jsonapi-1.0.3.post20',
]
setup(
...
dependency_links=dependency_links,
install_requires=requires,
....
)
```
> setup.py versioning improvements

- pyramid_jsonapi/jsonapi.py
- pyramid_jsonapi/metadata/JSONSchema.py
Add a method to return the jsonschema attributes for resources at a specified endpoint.
Add views/routes of the form: `/metadata/JSONSchema/routes/{endpoint}` which calls the above method.
`/metadata/JSONSchema` returns the JSONAPI jsonschema schema in full for external validation.
> Move jsonschema generation into metadata module.

- pyramid_jsonapi/__init__.py
- test_project/test_project/tests.py
db queries can also raise `ValueError`, e.g. if an `int` id is passed when the db expects `uuid`.
Handle this as well as `DataError`, and also add some tests to cover possible mistakes (note, there is no test to trigger ValueError, since I'm not sure how to trigger thsi with a test db that uses int ids).
It also looks like the code could be DRYer - `get` and `delete` methods use similar but different ways to query the DB, that could be reconciled.
> Handle bad ids in GET/DELETE.

- .pylintrc
- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
- pyramid_jsonapi/metadata/JSONSchema.py
- pyramid_jsonapi/metadata/__init__.py
- pyramid_jsonapi/settings.py
- test_project/development.ini
- test_project/test_project/__init__.py
- test_project/test_project/tests.py
- test_project/testing.ini
* New `pyramid_jsonapi.settings` module/class
* Stores default config values and descriptions
* Config available as class attributes
* attributes are of type `ConfString` - a class which maps `pyramid.settings` `asbool` and `aslist` rto be methods on the object.
* Pyramid config (inifile) overrides pyramid_jsonapi defaults - updated by key - preventing setting of unknown values in the config.
> Configuration settings moved to their own class

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/version.py
- setup.py
This allows us to have `pyramid_jsonapi.__version__` while still using `version.py` in setup.py etc.
> Move version.py into project.

- pyramid_jsonapi/settings.py
- travis/sphinx.sh
This creates `apidoc/settings.inc` on the fly during sphinx building - this is then included in the docstring docs for `pyramid_jsonapi.settings.Settings` (and can be included in README.rst if desired later).
This PR relies on `versioning` branch PR.
> Auto-generate settings docs in sphinx.

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
- pyramid_jsonapi/settings.py
Add response checking decorator to wrap view methods.
* Catch all exceptions, check if they are in the 'responses' lists
in the endpoints data or not.
* If not, raise a generic error, and log the real one.
* Otherwise, just re-raise.
> Check view responses are valid by schema, and 'hide' unexpected ones from the client.

- pyramid_jsonapi/__init__.py
Same exception-handling as in other places where db queries using client-provided id are used.
Alternatively we could raise `HTTPBadRequest` at this point, but elsewhere we treat invalid and missing ids as equivalent, so just return `False` here.
Note - in this and other places in the code we handle `StatementError` - however there's no way to test this in the current framework unless we have something like uuids in the test DB. These bugs are ones I'm just finding by chance through using uuids in other projects. This explains the coverage drop.
> Return false on DB errors querying ids.

- docs/source/developing.rst
- docs/source/index.rst
- docs/source/metadata.rst
Create 'human' docs for Metadata modules, with links to human docs for each module (currently just linking back to autodocs).
> Metadata docs

- docs/source/customisation.rst
- pyramid_jsonapi/endpoints.py
`route_pattern_suffix` in endpoints now replaced with `route_pattern` dict, containing `fields` (a list of fields in order of use in route path) and `pattern` (the python `format` string to use to join them. pattern can also contain `{sep}` which will be substituted with the route_separator (i.e. `/`)
> Refactor route_pattern_suffix.

- docs/source/api-creation.rst
- docs/source/client.rst
Add `api` to the start of example endpoints in the docs so that documentation matches new default behaviour.
> Add 'api' to beginning of example endpoints.

- pyramid_jsonapi/__init__.py
* `obj_id`, `item`, `relname`, `rel`, `rel_class` and rel_view now instance attrs
* Getting item from id and setting up rel info now in decorator
* `single_item_query` now a method, takes `loadonly` param
This change removes a large amount of duplicated code, and puts it into the decorator. The main advantages are that it is now DRYer, shorter code, and exceptions happen sooner.
The downsides are that there is always a db query for routes with id set - though in most cases this would have happened anyway (and see below for comment on this) - and that exceptions are slightly more generic (though still equally informative).
A few 'todos' are probably still needed:
* There are a few high-level db access methods (`single_item_query`, `single_return`, `collection_return` etc) but also a number …
> Refactor common code out of decorated methods

- README.rst
- docs/sphinx.sh
Note: This will need a new tag issuing on a commit to master to kick off the `travis-sphinx deploy` step which will update gh-pages. (Though this is probably needed anyway to make the docs reflect the current state of the `master` branch).
> Push sphinx badge to github gh-pages and remote-link.

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/filters.py
Moved class into a module, and moved `register` calls from `PyramidJSONAPI` into a method called from class' `__init__`
Module is called 'filters' as I have a feeling there may be other classes or methods related to filtering needed in the future, but can always rename later if this isn't the case.
> Move FilterRegistry into filters module.

- pyramid_jsonapi/collection_view.py
TODO: Add a test that meta fields (available, returned etc) match actual db counts.
> Use doc.resources list, not constructed data dict, for returned count.

- pyramid_jsonapi/collection_view.py
Just checked, and while the total length is 2261 lines, the actual code without docstrings is only 627, so it's just not an issue :smiley:
> Ignore too-many-lines

- pyramid_jsonapi/collection_view.py
Refactor serialise_db_item to use a more uniform code path for all relationship types when serialising related items.
This refactoring exposed a bug when serialising items using joined table inheritance. 3fde516 fixes that bug.
> Tidy serialise

- docs/source/metadata.rst
- docs/sphinx.sh
- pyramid_jsonapi/metadata/__init__.py
- pyramid_jsonapi/settings.py
- test_project/test_project/tests.py
* Use settings `metadata_modules` as definitive list.
* allows no modules to be loaded.
* Set default value to JSONSchema and OpenAPI
* Add tests to handle behaviour if modules not added.
(Also added unrelated pylint badge fix in this PR).
> Make metadata module loading explicit.

- .travis.yml
Previous setting of `branch: master` means that pypi gets a new deployment on every master commit, but these will be ignored by pypi unless the tag has changed.
However, when a new tagged release is pushed, travis sees the branch as having the name of the tag, and thus explicitly doesn't deploy to pypi.
This fixes this issue, though it does pin us to only using 'stable' tags when we wish to make a release, and must use `dev` etc tags at other times if required.
> Deploy to pypi on new tags.

- pyramid_jsonapi/version.py
pip and OS packages (deb, rpm etc) remove of move PKG-INFO to a different location. However the package can then be discovered using `pkg_resources`.
Add code to handle missing PKG-INFO and try `pkg_resources.get_distribution` instead.
> Extend version.py to handle installations. Fixes #140

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
- test_project/test_project/tests.py
If set, use in path construction (defaults to `''`).
Later PR will extend this to be the `version` value used in OpenAPI.
> Add api_version configuration option

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
Some steps to simplify the methods and their calling, and remove the legacy 'route_info' dict and use settings directly.
> Refactor RoutePatternConstructor

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
- pyramid_jsonapi/metadata/OpenAPI/__init__.py
(Relies on #145 being merged first...)
* Use the `api_version` in the openapi spec (falling back to application version if unspecified).
* Handle the presence of a `base` prefix (i.e. if proxied from a subdirectory) in generating endpoint info and URLs for testing.
> Versioning and Proxied paths for OpenAPI

- .travis.yml
- pyramid_jsonapi/metadata/JSONSchema/__init__.py
It appeared that there were some inefficiencies in calling JSONSchema methods repeatedly (for example from the OpenAPI module) due to the use of `copy.deepcopy` to make modified copies of the schema dict for different endpoints.
The performance is good under python >= `3.6` but poor on `3.5` and below - `3.6` has had a lot of optimisations in both `dict` handling and `deepcopy`, not least moving many of these functions into dedicated C libraries.
The easiest 'fix' for this is to use `pickle` instead of `deepcopy`. Doing a `pickle.loads(pickle.dumps(x))` is fast as it all happens in C, and while it is not a universal equivalent to `deepcopy`, it is safe in this instance since the schema is JSON in origin so shouldn't contain any things which `pickle` might baulk at.
Performance in …
> JSONSchema optimisations

- pyramid_jsonapi/__init__.py
- test_project/test_project/tests.py
These views now act only on paths that `pyramid_jsonapi` believes it controls - namely paths starting with `route_pattern_api_prefix` and `route_pattern_metadata_prefix` between slashes (or `/api/` and `/metadata/` by default).
fixes #151
> Error, notfound and forbidden views registered for more specific paths

- .travis.yml
From https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes:
* W503 (*)	line break before binary operator
* W504 (*)	line break after binary operator
(*) In the default configuration, the checks ... W503 and W504 ... are ignored because they are not rules unanimously accepted, and PEP 8 does not enforce them.
Not sure why they're now catching, so explicitly disable them.
Merging this PR should cause the other pending PRs to pass travis (I hope!)
> Ignore errors about binary operator breaks.

- pyramid_jsonapi/metadata/OpenAPI/__init__.py
If no `home_page` metadata value is specified, use the current base url that the OpenAPI docs are being served from as the API root in the specification.
> Use host_url as openapi api base url

- pyramid_jsonapi/__init__.py
- pyramid_jsonapi/endpoints.py
- test_project/test_project/tests.py
- tox.ini
Tidy up the creation of views:
- Use `route_pattern_prefix` in view path if specified.
- Use the (modified) `pattern_from_components` method (shorter and DRYer).
- Add tests for the various prefixes, and their error states.
- Misc test tidying and tox fixes.
> View construction fixes

- docs/source/customisation.rst
- pyramid_jsonapi/__init__.py
- test_project/test_project/tests.py
The same issue as fixed in the previous PR, but for `api_version`.
Also added documentation for `URL Paths` to explain how the prefixes get combined.
*Note*: We'll need a tag added to `master` once this is merged to get the docs updated and a new release with these fixes in.
> Add api_version to view construction

- pyramid_jsonapi/collection_view.py
- test_project/development.ini
- test_project/test_project/models.py
- test_project/test_project/test_data.json
- test_project/test_project/tests.py
Fixes a problem where tables with relationships back to themselves would not work in one direction. For example, for a TreeNode realised with the adjacency list pattern, the relationship 'parent' would always return null.
> Fix adjacancy

- test_project/test_project/tests.py
There is a small typo in test_project/test_project/tests.py.
Should read `foreign` rather than `forreign`.
> docs: Fix simple typo, forreign -> foreign

- pyramid_jsonapi/__init__.py
Allows primary key to be defined by doing e.g.:
`__pyramid_jsonapi__['id_col_name'] = 'col_name'`
There's no documentation included in this just yet - let me know if I should update the docs, or if you just want to make a note to do this in the 2_2 docs overhaul.
> Refactor to allow setting id_col_name in model
