colinhiggs/pyramid-jsonapi

pyramid_jsonapi/__init__.py
requirements.txt
setup.py
test_project/setup.py

- Remove psycopg2 from pyramid_jsonapi
- Re-order dependency imports (pylint)
- Split requirements.txt for code and tests

Various Dependency Fixes

---

.travis.yml
pyramid_jsonapi/__init__.py

* Be explicit about what CollectionView Base attributes should exist.
* Misc pylint fixes
* Enable pylint validation in travis (errors only, won't complain about style issues, warnings etc).

More pylint fixes

---

pyramid_jsonapi/__init__.py

Tidy up, collapsing things like:
```
if x is None:
x = 1
foo(x)
```
To 
`foo(x or 1)`

Refactor 'if is None' tests

---

.pylintrc
.travis.yml
pyramid_jsonapi/__init__.py

- Build class_attrs dict, then pass to type() at end
- More efficient way to build classes
- Removes need for CollectionView variable

Restructure collection_view_factory()

---

pyramid_jsonapi/__init__.py

- Create `id_col_name` in `__pyramid_jsonapi__` dict attr in model
`- id_col()` convenience method in `CollectionViewBase`

Refactor away _jsonapi_id

---

pyramid_jsonapi/__init__.py

- main schema loaded on api creation and stored
- left scope to add view and method specific schemas later

Don't reload schema with every request.

---

pyramid_jsonapi/__init__.py
pyramid_jsonapi/callbacks_doc.py
pyramid_jsonapi/endpoints.py

https://www.python.org/dev/peps/pep-0257/
`For consistency, always use """triple double quotes""" around docstrings.`

Switch to triple double quotes for docstrings.

---

pyramid_jsonapi/__init__.py

`maxsize=128` is the default for `lru_cache`

Remove setting of a default value.

---

pyramid_jsonapi/settings.py
test_project/test_project/__init__.py
test_project/test_project/tests.py
test_project/testing.ini

* complete descriptions for various defaults
* remove unused defaults
* rename setting that was for the test project

Settings documentation

---

README.rst
developing.md
docs/source/conf.py

Various updates to deal with changes for `metadata` branch.
Still need to decide how to update the developer docs, for things including:
* `metadata` endpoints
* `responses` in endpoint data.
* `jsonapi` class objects.

Misc doc updates.

---

pyramid_jsonapi/settings.py
travis/sphinx.sh

Make method return string rather than printing it.

---

pyramid_jsonapi/settings.py
test_project/test_project/tests.py
travis/sphinx.sh

Some tests for the settings module (relies on PR #86 to be merged).

Settings tests

---

pyramid_jsonapi/__init__.py
pyramid_jsonapi/endpoints.py
test_project/test_project/tests.py

Fixes to exceptions, docstrings and more tests. Failing test is result of issue #90

Misc fixes

---

.pylintrc
pyramid_jsonapi/__init__.py

Also update pylint to ignore dynamic attributes in `MetaData`

Use JSONSchema metadata plugin for schema.

---

pyramid_jsonapi/__init__.py

We need to move instantiation of metadata module to after calling `create_resource` so that `view_classes` is populated (needed for `OpenAPI` work).
Begin by refactoring:
* Create a single `api` attribute in `CollectionViewBase`, and remove separate attributes which are all children of `api`.
Todo: fix get_dbsession issue and actually move metadata instantiation.

Refactor metadata import and api class access.

---

pyramid_jsonapi/__init__.py

Address the missing docstring messages from pylint.

Pylint docstrings

---

pyramid_jsonapi/__init__.py
test_project/test_project/tests.py

Add support for filtering on related objects

---

pyramid_jsonapi/endpoints.py

* Remove defaults in RoutePatternConstructor to prevent duplicates with
settings.py
* Make a route_info dict, to hold settings and make passing easier.
* Rename main_pattern to confirm with naming elsewhere.
* Improves pylint score by removeing instance attrs.

Refactor route information in endpoints

---

pyramid_jsonapi/collection_view.py

PR to add useful bugfixes and features extracted from the diverged PRs.
I've added a message to his PR saying that basically we're going to close them with only a breif glance, but that we'd be keen to know if 2.x will be something he can use (or if it is missing any features).
I've had a scan through his commits and can only see one bug, which I've patched - the rest are either for no-longer-existing code, or make changes that break spec or add features that aren't supoorted.
There are a few commits that might be worth you casting an eye over, since they are adding something that is potentially useful, or dealing with a situation I don't understand:
https://github.com/colinhiggs/pyramid-jsonapi/pull/34/commits/5751ed9bf63e77f9b4a34672b1498c57a7afd06f
This uses a regex with word …

amichayoren PRs

---

pyramid_jsonapi/__init__.py
pyramid_jsonapi/settings.py
test_project/test_project/tests.py

Add the option to expose foreign key columns in attributes. This addresses #125.

Expose foreign keys

---

pyramid_jsonapi/metadata/JSONSchema/__init__.py

`deepcopy` less deeply, only construct `schema_post` once. Adds another order of magnitude speedup to generating the OpenAPI specification.

More endpoint optimisations.

---

buildout.cfg
test_project/development.ini
test_project/run-app.py

Add test_project/run-app.py which sets up a local test database using `testing.postgresql` befare launching the test_project app.

run dev mode with local test database

---

pyramid_jsonapi/collection_view.py

Workaround for https://github.com/kvesteri/sqlalchemy-utils/issues/440
Results in identical SQL generation.

Use filter instead of get.
